"""Add content preview fields for hybrid storage

Revision ID: b8a80815529b
Revises: 4336d28454a2
Create Date: 2025-10-26 08:13:04.283990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a80815529b'
down_revision: Union[str, None] = '4336d28454a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content_preview', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('has_full_content_in_graph', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'has_full_content_in_graph')
    op.drop_column('notes', 'content_preview')
    # ### end Alembic commands ###
